import { useQuery, useMutation, useAction } from 'convex/react';

// The @convex alias points to ../backend/convex/_generated (configured in vite.config.js)
// This file is auto-generated by `npx convex dev` — run that first!
// eslint-disable-next-line import/no-unresolved
import { api } from '@convex/api';

/**
 * Hook for fetching merch catalog
 * @param {string|undefined} category - 'hoodie' | 'cap' | 'sticker' | 'limited'
 */
export function useMerch(category) {
  return useQuery(api.functions.merch.getMerch, {
    category: category || undefined,
  });
}

/**
 * Hook for featured merch (homepage)
 */
export function useFeaturedMerch() {
  return useQuery(api.functions.merch.getFeaturedMerch, {});
}

/**
 * Hook for placing an order
 */
export function usePlaceOrder() {
  return useMutation(api.functions.orders.placeOrder);
}

/**
 * Hook for user's order history
 */
export function useUserOrders(userId) {
  return useQuery(
    api.functions.orders.getUserOrders,
    userId ? { userId } : 'skip'
  );
}

/**
 * Hook for fetching media
 * @param {string|undefined} type
 * @param {string|undefined} platform
 */
export function useMedia(type, platform) {
  return useQuery(api.functions.media.getMedia, {
    type: type || undefined,
    platform: platform || undefined,
  });
}

/**
 * Hook for submitting collab/contact form
 */
export function useSubmitCollab() {
  return useMutation(api.functions.collab.submitCollabForm);
}

/**
 * Hook for brand story content (About page)
 */
export function useBrandStory() {
  return useQuery(api.functions.brandContent.getBrandStory, {});
}

/**
 * Hook for brand philosophy cards
 */
export function usePhilosophy() {
  return useQuery(api.functions.brandContent.getPhilosophy, {});
}

/**
 * Hook for timeline entries
 */
export function useTimeline() {
  return useQuery(api.functions.brandContent.getTimeline, {});
}

/**
 * Hook for creating a Stripe checkout session
 */
export function useStripeCheckout() {
  return useAction(api.functions.stripe.createCheckoutSession);
}
